---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

# command to view the service details and get the external IP
# kubectl get svc nginx-service -o wide

# command to view the service in minikube and get the URL
# minikube service nginx-service --url
